# Site settings
title: Community Data Toolkit Workshop
email: rdm@mcmaster.ca
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/CDTW" # the subpath of your site, e.g. /blog/
url: "https://community-data-toolkits-workshop.github.io" # the base hostname & protocol for your site
twitter_username: macscds
github_username:  Community-Data-Toolkits-Workshop

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Other options
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

exclude:
- _site/